# Generated by Django 4.2.13 on 2024-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
